# cpp_ex2

Acording to the fourm, in the program we should have try and catch - need to check where I need to add this.
(maybe in factory when creating new object)
but this can be resolved by std::nothrow
